name: Build Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' 

  workflow_dispatch:

jobs:

  configura-dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Usando .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.

  build-workflow:
    runs-on: ubuntu-latest
    needs: configura-dotnet
    steps:
      - uses: actions/checkout@v4
      - name: Builda Webapp
        run: dotnet build **/*.csproj

  roda-workflow:
      runs-on: ubuntu-latest
      needs: build-workflow
      steps:
        - name: Roda Webapp
          run: dotnet run --project /workspaces/github-actions-dotnet-webapp/github4women/github4women.csproj 