name: Build Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' 

  workflow_dispatch:

jobs:

  configura-dotenet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Usando .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.
      - name: Restaurar dependências
        run: dotnet restore


  build-workflow:
    runs-on: ubuntu-latest
    needs: configura-dotenet
    steps:
      - uses: actions/checkout@v4
      - name: Builda Webapp
        run: dotnet build **/*.csproj --no-restore

  roda-workflow:
      runs-on: ubuntu-latest
      needs: build-workflow
      steps:
        - name: Roda Webapp
          run: dotnet run --project **/*.csproj