name: Build Workflow

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 * * * *' 

  workflow_dispatch:

jobs:

  configura-dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Usando .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

  build-workflow:
    runs-on: ubuntu-latest
    needs: configura-dotnet
    steps:
      - uses: actions/checkout@v4
      - name: Restaura dependencias
        run: |
          echo "Restaurando dependências"
          dotnet restore ./github4women/github4women.csproj
      - name: Builda Webapp
        run: dotnet build ./github4women/github4women.csproj --no-restore